import type { CatalogItem } from '../domain/item';

/**
 * Curated, version-controlled item catalog for the MVP's 10 supported
 * champions. This is the bundled fallback used when Data Dragon can't be
 * reached (see data-dragon-service) and the source of the curated fields
 * (categories, countersThreatTags, bestPhases, mutual-exclusion groups)
 * that Data Dragon's raw JSON doesn't express. Item ids match live Data
 * Dragon ids so a real fetch can merge in fresh names/prices/icons without
 * changing this scoring metadata.
 */
export const ITEM_CATALOG: CatalogItem[] = [
  {
    id: 3031,
    name: "Infinity Edge",
    totalPrice: 3400,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['PHYSICAL_DAMAGE'],
    stats: { attackDamage: 70, criticalChancePercent: 25 },
    buildsFrom: [1037, 1038],
    hasUniqueEffect: false,
    countersThreatTags: [],
    bestPhases: ['MID', 'LATE'],
    iconId: '3031.png',
  },
  {
    id: 6672,
    name: "Kraken Slayer",
    totalPrice: 3400,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['PHYSICAL_DAMAGE', 'ATTACK_SPEED'],
    stats: { attackDamage: 45, attackSpeedPercent: 40 },
    buildsFrom: [1042, 1037],
    hasUniqueEffect: true,
    countersThreatTags: ['TANK'],
    bestPhases: ['MID', 'LATE'],
    iconId: '6672.png',
  },
  {
    id: 3142,
    name: "Youmuu's Ghostblade",
    totalPrice: 2900,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['PHYSICAL_DAMAGE', 'ATTACK_SPEED'],
    stats: { attackDamage: 55, attackSpeedPercent: 20 },
    buildsFrom: [1037, 1042],
    hasUniqueEffect: true,
    countersThreatTags: [],
    bestPhases: ['EARLY', 'MID'],
    iconId: '3142.png',
  },
  {
    id: 3071,
    name: "Black Cleaver",
    totalPrice: 3000,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['PHYSICAL_DAMAGE', 'HEALTH'],
    stats: { attackDamage: 55, health: 300, abilityHaste: 15 },
    buildsFrom: [1037, 1028],
    hasUniqueEffect: true,
    countersThreatTags: ['TANK'],
    bestPhases: ['MID', 'LATE'],
    iconId: '3071.png',
  },
  {
    id: 6694,
    name: "Serylda's Grudge",
    totalPrice: 3200,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['PHYSICAL_DAMAGE'],
    stats: { attackDamage: 45, abilityHaste: 15, armor: 0 },
    buildsFrom: [1037, 1033],
    hasUniqueEffect: true,
    countersThreatTags: ['TANK'],
    bestPhases: ['MID', 'LATE'],
    iconId: '6694.png',
  },
  {
    id: 6655,
    name: "Luden's Companion",
    totalPrice: 3200,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['MAGIC_DAMAGE', 'ABILITY_HASTE'],
    stats: { abilityPower: 80, abilityHaste: 15 },
    buildsFrom: [1052, 1058],
    hasUniqueEffect: true,
    countersThreatTags: [],
    bestPhases: ['EARLY', 'MID'],
    iconId: '6655.png',
  },
  {
    id: 3089,
    name: "Rabadon's Deathcap",
    totalPrice: 3600,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['MAGIC_DAMAGE'],
    stats: { abilityPower: 130 },
    buildsFrom: [1058, 1058],
    hasUniqueEffect: true,
    countersThreatTags: [],
    bestPhases: ['MID', 'LATE'],
    iconId: '3089.png',
  },
  {
    id: 4645,
    name: "Shadowflame",
    totalPrice: 3300,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['MAGIC_DAMAGE'],
    stats: { abilityPower: 100 },
    buildsFrom: [1058, 1026],
    hasUniqueEffect: true,
    countersThreatTags: [],
    bestPhases: ['MID', 'LATE'],
    iconId: '4645.png',
  },
  {
    id: 3135,
    name: "Void Staff",
    totalPrice: 2800,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['MAGIC_DAMAGE'],
    stats: { abilityPower: 65 },
    buildsFrom: [1058, 1026],
    hasUniqueEffect: false,
    countersThreatTags: ['TANK'],
    bestPhases: ['MID', 'LATE'],
    iconId: '3135.png',
  },
  {
    id: 3075,
    name: "Thornmail",
    totalPrice: 2700,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['ARMOR', 'ANTI_HEAL'],
    stats: { armor: 60, health: 350 },
    buildsFrom: [1031, 1028],
    hasUniqueEffect: true,
    countersThreatTags: ['SUSTAINED', 'HEALING'],
    bestPhases: ['EARLY', 'MID'],
    iconId: '3075.png',
  },
  {
    id: 3143,
    name: "Randuin's Omen",
    totalPrice: 2900,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['ARMOR', 'HEALTH'],
    stats: { armor: 60, health: 400 },
    buildsFrom: [1031, 1028],
    hasUniqueEffect: true,
    countersThreatTags: ['BURST'],
    bestPhases: ['MID', 'LATE'],
    iconId: '3143.png',
  },
  {
    id: 3068,
    name: "Sunfire Aegis",
    totalPrice: 3200,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['ARMOR', 'HEALTH'],
    stats: { armor: 45, magicResist: 0, health: 450 },
    buildsFrom: [1031, 1057],
    hasUniqueEffect: true,
    countersThreatTags: ['TANK'],
    bestPhases: ['EARLY', 'MID'],
    iconId: '3068.png',
  },
  {
    id: 3047,
    name: "Plated Steelcaps",
    totalPrice: 1100,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['ARMOR', 'MOVEMENT'],
    stats: { armor: 25 },
    buildsFrom: [1001, 1029],
    mutuallyExclusiveGroup: 'BOOTS',
    hasUniqueEffect: false,
    countersThreatTags: [],
    bestPhases: ['EARLY'],
    iconId: '3047.png',
  },
  {
    id: 3111,
    name: "Mercury's Treads",
    totalPrice: 1100,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['MAGIC_RESIST', 'MOVEMENT'],
    stats: { magicResist: 25 },
    buildsFrom: [1001, 1033],
    mutuallyExclusiveGroup: 'BOOTS',
    hasUniqueEffect: false,
    countersThreatTags: ['HARD_CC'],
    bestPhases: ['EARLY'],
    iconId: '3111.png',
  },
  {
    id: 3102,
    name: "Spirit Visage",
    totalPrice: 2900,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['MAGIC_RESIST', 'HEALTH'],
    stats: { magicResist: 55, health: 350 },
    buildsFrom: [1033, 1057],
    hasUniqueEffect: true,
    countersThreatTags: [],
    bestPhases: ['MID', 'LATE'],
    iconId: '3102.png',
  },
  {
    id: 8020,
    name: "Force of Nature",
    totalPrice: 2900,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['MAGIC_RESIST', 'HEALTH', 'MOVEMENT'],
    stats: { magicResist: 70, health: 350 },
    buildsFrom: [1033, 1057],
    hasUniqueEffect: true,
    countersThreatTags: [],
    bestPhases: ['MID', 'LATE'],
    iconId: '8020.png',
  },
  {
    id: 3165,
    name: "Morellonomicon",
    totalPrice: 2500,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['MAGIC_DAMAGE', 'ANTI_HEAL'],
    stats: { abilityPower: 70, health: 250 },
    buildsFrom: [1052, 3801],
    hasUniqueEffect: true,
    countersThreatTags: ['SUSTAINED', 'HEALING'],
    bestPhases: ['EARLY', 'MID'],
    iconId: '3165.png',
  },
  {
    id: 3123,
    name: "Executioner's Calling",
    totalPrice: 1300,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['PHYSICAL_DAMAGE', 'ANTI_HEAL'],
    stats: { attackDamage: 15 },
    buildsFrom: [1036],
    hasUniqueEffect: true,
    countersThreatTags: ['SUSTAINED', 'HEALING'],
    bestPhases: ['EARLY', 'MID'],
    iconId: '3123.png',
  },
  {
    id: 3083,
    name: "Warmog's Armor",
    totalPrice: 3000,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['HEALTH'],
    stats: { health: 800 },
    buildsFrom: [1028, 1028],
    hasUniqueEffect: true,
    countersThreatTags: ['BURST'],
    bestPhases: ['MID', 'LATE'],
    iconId: '3083.png',
  },
  {
    id: 3084,
    name: "Heartsteel",
    totalPrice: 3200,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['HEALTH'],
    stats: { health: 450, abilityHaste: 15 },
    buildsFrom: [1028, 1011],
    hasUniqueEffect: true,
    countersThreatTags: ['BURST'],
    bestPhases: ['MID', 'LATE'],
    iconId: '3084.png',
  },
  {
    id: 3109,
    name: "Knight's Vow",
    totalPrice: 2000,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['HEALTH', 'TEAM_UTILITY'],
    stats: { health: 300 },
    buildsFrom: [1028, 1006],
    hasUniqueEffect: true,
    countersThreatTags: [],
    bestPhases: ['EARLY', 'MID'],
    iconId: '3109.png',
  },
  {
    id: 3190,
    name: "Locket of the Iron Solari",
    totalPrice: 2400,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['ARMOR', 'MAGIC_RESIST', 'TEAM_UTILITY'],
    stats: { armor: 30, magicResist: 30 },
    buildsFrom: [1033, 1031],
    hasUniqueEffect: true,
    countersThreatTags: ['BURST'],
    bestPhases: ['EARLY', 'MID'],
    iconId: '3190.png',
  },
  {
    id: 3107,
    name: "Redemption",
    totalPrice: 2300,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['HEALTH', 'TEAM_UTILITY'],
    stats: { health: 200 },
    buildsFrom: [1028, 3801],
    hasUniqueEffect: true,
    countersThreatTags: ['BURST'],
    bestPhases: ['MID', 'LATE'],
    iconId: '3107.png',
  },
  {
    id: 6617,
    name: "Moonstone Renewer",
    totalPrice: 2300,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['TEAM_UTILITY', 'ABILITY_HASTE'],
    stats: { abilityPower: 45, abilityHaste: 10 },
    buildsFrom: [1052, 3801],
    hasUniqueEffect: true,
    countersThreatTags: [],
    bestPhases: ['EARLY', 'MID'],
    iconId: '6617.png',
  },
  {
    id: 3084 + 1,
    name: "Frozen Heart",
    totalPrice: 2500,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['ARMOR', 'MANA', 'ABILITY_HASTE'],
    stats: { armor: 70, abilityHaste: 15 },
    buildsFrom: [1011, 1006],
    hasUniqueEffect: true,
    countersThreatTags: ['TANK'],
    bestPhases: ['MID', 'LATE'],
    iconId: '3110.png',
  },
  {
    id: 3742,
    name: "Dead Man's Plate",
    totalPrice: 2900,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['ARMOR', 'HEALTH', 'MOVEMENT'],
    stats: { armor: 45, health: 300 },
    buildsFrom: [1031, 1028],
    hasUniqueEffect: true,
    countersThreatTags: [],
    bestPhases: ['EARLY', 'MID'],
    iconId: '3742.png',
  },
  {
    id: 6656,
    name: "Everfrost",
    totalPrice: 2900,
    purchasable: true,
    availableOnSummonersRift: true,
    categories: ['MAGIC_DAMAGE', 'CROWD_CONTROL_UTILITY', 'HEALTH'],
    stats: { abilityPower: 70, health: 250, abilityHaste: 10 },
    buildsFrom: [1052, 1026],
    hasUniqueEffect: true,
    countersThreatTags: [],
    bestPhases: ['EARLY', 'MID'],
    iconId: '6656.png',
  },
];

export function findCatalogItem(itemId: number): CatalogItem | undefined {
  return ITEM_CATALOG.find((item) => item.id === itemId);
}
